### ISSUE TITLE
Suggested modifications to speed up the spack pipelines

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#171]
A few ideas to speed up the spack pipelines:

1. only re-build base image if it doesn't exist
1. cache a spack.lock so we don't have to concretize

1 is definitely a no brainer, and should be done.

2 is a little more complicated. You would need to remember to remove that file when you update the spack submodule. Additionally we would have to maintain a lock file for each build in the matrix.

_Originally posted by @cameronrutherford in https://github.com/ORNL/ReSolve/issues/170#issuecomment-2182896813_

**Comment by cameronrutherford** [comment]
I don't think part 2 is feasible / reasonable. We want to still re-build with spack in each PR so that testing is run, and to make sure that nothing is broken. It's a little annoying the concretizer takes a while, but I don't think it's worth the lift to try and work around this.

The only improvement that might be worth considering is only pushing to the registry if we are merging a PR into a core development branch. If we want this, then we should consider a new issue.
