### ISSUE TITLE
Should CI pipelines assume CUDA support is turned on by default?

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#31]
Consider setting CMake variable `-D RESOLVE_USE_CUDA=On` explicitly when setting up CI tests. It is probably better if the CUDA support is off by default and have users turn it on depending on their configurations.

CC @kswirydo @cameronrutherford

**Comment by cameronrutherford** [comment]
https://github.com/ORNL/ReSolve/blob/develop/CMakePresets.json#L10 - since we have a base cuda build here, would be a few lines to add CMake cache variable to JSON, and then disabling the variable by default.

Note this affects how our current spack package would behave, and so that would also need to be updated

**Comment by cameronrutherford** [comment]
https://github.com/spack/spack/pull/40149
